spring:
  application:
    name: rangero
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/rangero
    username: ${db_username}
    password: ${db_password}
  jpa:
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
  servlet:
    multipart:
      max-file-size: 8MB
      max-request-size: 9MB


aws:
  accessKey: ${aws_access_key}
  secretKey: ${aws_secret_access_key}
  region: ${aws_region}}
  bucketName: ${aws_bucket_name}

logging:
  level:
    root: debug

springdoc:
  swagger-io.path: /swagger-ui.html

security:
  secret: ${secret_key}







