spring:
  application:
    name: rangero
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/rangero
    username: ${db_username}
    password: ${db_password}
  jpa:
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
  sql:
    init:
      mode: always


logging:
  level:
    root: debug


security:
  secret: ${secret_key}







